version: '3'

volumes:
  postgres_volume:

services:
  auth_db:
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - local.env
    ports:
      - "6432:5432"

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    restart: on-failure
    env_file:
      - local.env
    environment:
      DB_HOST: auth_db

